Change upload functionality to use Google Cloud Store, re #9065
icplayer/icfoundation pull request #28
Opened 2024-01-16 12:35 UTC by msawoniuk

[Ticket](https://learneticsa.assembla.com/spaces/lorepo/tickets/9065)
PR icplayer
PR iceditor
PR icfoundation

[Wersja testowa](https://test-9065-dot-mauthor-dev.ew.r.appspot.com/)

2024-01-16 12:43 UTC, msawoniuk commented on src/main/java/com/lorepo/icf/widgets/UploadFileDlg.java
Zmienioną funkcjonalność przeniosłem do repozytorium AddonEditor z 3 powodów.
1. Funkcjonalność ta była wykorzystywana tylko w AddonEditor. 
2. Brak możliwości dopasowania funkcjonalności, aby korzystała z AppController (AddonEditor i player/editor mają osobne ich reprezentacje). AppController wykorzystuję do wyświetlania informacji o błędzie.
3. Trudności z obejściem tego, aby requesty były wysyłane poza akcjami.

2024-01-17 07:52 UTC, wkarasSolwit requested changes
usunięcie loga

2024-01-17 07:52 UTC, wkarasSolwit commented on src/main/java/com/lorepo/icf/utils/FileUploader.java
> +                console.log(inputs[i].getAttribute("name"));
zbędny log

2024-01-18 07:54 UTC, msawoniuk commented on src/main/java/com/lorepo/icf/utils/FileUploader.java
> +                console.log(inputs[i].getAttribute("name"));
ok

2024-01-18 09:38 UTC, wkarasSolwit approved these changes
OK

2024-01-19 12:23 UTC, merged